kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: test backend
    image: eclipse-temurin:17
    commands:
      - cd backend
      - chmod +x gradlew
      - ./gradlew test
