version: "3.8"

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    depends_on:
      - backend
    networks:
      - public
      - comp6000
    environment:
      - VUE_APP_API_URL=backend
      - VUE_APP_API_PORT=8080
    ports:
      - "80:80"

  backend:
    container_name: backend
    restart: always
    build: ./backend
    networks:
      - public
      - comp6000
    environment:
      - API_WS_SCHEMATIC_ENDPOINT=/ws/schematics
    ports:
      - "8080:8080"

  minecraft-server:
    container_name: minecraft-server
    build: minecraft-server
    restart: always
    depends_on:
      - backend
    networks:
      - comp6000
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=9090
    volumes:
      - ./bukkit-plugin/build/libs/comp6000-bukkit.jar:/minecraft-server/plugins/bukkit-plugin.jar:ro
    ports:
      - "25565:25565"

networks:
  public:
    external: true
  comp6000: