version: "3.8"

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    networks:
      - public
      - comp6000
    environment:
      - API_WS_SCHEMATIC_ENDPOINT=/ws/schematics
    ports:
      - "8080:8080"

  minecraft-server:
    container_name: minecraft-server
    build: minecraft-server
    restart: always
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M
    networks:
      - comp6000
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=9090
    volumes:
      - ./bukkit-plugin/build/libs/comp6000-bukkit.jar:/minecraft-server/plugins/bukkit-plugin.jar:ro
    ports:
      - "25565:25565"

networks:
  public:
    external: true
  comp6000: