server:
  error:
    include-message: always

limits:
  building:
    height:
      min: ${BUILDING_HEIGHT_MIN:10}
      max: ${BUILDING_HEIGHT_MAX:40}

api:
  ws:
    schematics:
      endpoint: ${API_WS_SCHEMATIC_ENDPOINT:/ws/schematics}

features:
  floors:
    - displayName:
      name: stone
      path: /some/path/features/floor/stone.sch
    - displayName:
      name: oak
      path: /some/path/features/floor/oak.sch
    - displayName:
      name: brick
      path: /some/path/features/floor/brick.sch
    - displayName: Stone Brick
      name: stonebrick
      path: /some/path/features/floor/stonebrick.sch
    - displayName:
      name: marble
      path: /some/path/features/floor/marble.sch
    - displayName:
      name: sandstone
      path: /some/path/features/floor/sandstone.sch
    - displayName: Smooth Stone
      name: smoothstone
      path: /some/path/features/floor/smoothstone.sch
    - displayName:
      name: wool
      path: /some/path/features/floor/wool.sch
    - displayName: Polished Andesite
      name: polishedandesite
      path: /some/path/features/floor/polishedandesite.sch
    - displayName:
      name: diorite
      path: /some/path/features/floor/diorite.sch
  walls:
    - displayName:
      name: brick
      path: /some/path/features/wall/brick.sch
    - displayName:
      name: oak
      path: /some/path/features/wall/oak.sch
    - displayName:
      name: marble
      path: /some/path/features/wall/marble.sch
    - displayName: Smooth Stone
      name: smoothstone
      path: /some/path/features/wall/smoothstone.sch
    - displayName: Stone Brick
      name: stonebrick
      path: /some/path/features/wall/stonebrick.sch
    - displayName:
      name: cobblestone
      path: /some/path/features/wall/cobblestone.sch
    - displayName:
      name: quartz
      path: /some/path/features/wall/quartz.sch
    - displayName: Nether Brick
      name: netherbrick
      path: /some/path/features/wall/netherbrick.sch
    - displayName:
      name: granite
      path: /some/path/features/wall/netherbrick.sch
    - displayName: Polished Limestone
      name: polishedlimestone
      path: /some/path/features/wall/polishedlimestone.sch
  doors:
    - name: oak
      path: /some/path/features/door/oak.sch
    - name: iron
      path: /some/path/features/door/iron.sch
    - name: spruce
      path: /some/path/features/door/spruce.sch
    - name: birch
      path: /some/path/features/door/birch.sch
    - name: jungle
      path: /some/path/features/door/jungle.sch
    - name: acacia
      path: /some/path/features/door/acacia.sch
    - name: darkoak
      path: /some/path/features/door/darkoak.sch
    - name: crimson
      path: /some/path/features/door/crimson.sch
    - name: warped
      path: /some/path/features/door/warped.sch
  roof:
    - name: oak
      path: /some/path/features/roof/oak.sch
    - name: spruce
      path: /some/path/features/roof/spruce.sch
    - name: birch
      path: /some/path/features/roof/birch.sch
    - name: acacia
      path: /some/path/features/roof/acacia.sch
    - name: darkoak
      path: /some/path/features/roof/darkoak.sch
    - name: hay
      path: /some/path/features/roof/hay.sch
    - name: smoothred
      path: /some/path/features/roof/smoothred.sch
    - name: brick
      path: /some/path/features/roof/brick.sch
    - name: smoothquartz
      path: /some/path/features/roof/smoothquartz.sch
    - name: cutcopper
      path: /some/path/features/roof/cutcopper.sch
  corners:
    - name: oak
      path: /some/path/features/corner/oak.sch
    - name: brick
      path: /some/path/features/corner/brick.sch
    - name: marble
      path: /some/path/features/corner/marble.sch
    - name: smoothstone
      path: /some/path/features/corner/smoothstone.sch
    - name: stonebrick
      path: /some/path/features/corner/stonebrick.sch
    - name: cobblestone
      path: /some/path/features/corner/cobblestone.sch
    - name: quartz
      path: /some/path/features/corner/quartz.sch
    - name: netherbrick
      path: /some/path/features/corner/netherbrick.sch
    - name: granite
      path: /some/path/features/corner/netherbrick.sch
    - name: polishedlimestone
      path: /some/path/features/corner/polishedlimestone.sch
  doornum:
    - name: 0
      path: /some/path/features/doornum/0.sch
    - name: 1
      path: /some/path/features/doornum/1.sch
    - name: 2
      path: /some/path/features/doornum/2.sch
  window:
    - name: 1x1
      path: /some/path/features/window/1x1.sch
    - name: 2x2
      path: /some/path/features/window/2x2.sch
    - name: 3x3
      path: /some/path/features/window/3x3.sch
    - name: 2x3
      path: /some/path/features/window/2x3.sch
    - name: 3x2
      path: /some/path/features/window/3x2.sch
    - name: 1x2
      path: /some/path/features/window/1x2.sch
    - name: 1x3
      path: /some/path/features/window/1x3.sch
    - name: 2x1
      path: /some/path/features/window/2x1.sch
    - name: 3x1
      path: /some/path/features/window/3x1.sch
    - name: lshape
      path: /some/path/features/window/lshape.sch
  bed:
    - name: red
      path: /some/path/features/red.sch
    - name: white
      path: /some/path/features/white.sch
    - name: orange
      path: /some/path/features/orange.sch
    - name: magenta
      path: /some/path/features/magenta.sch
    - name: blue
      path: /some/path/features/blue.sch
    - name: yellow
      path: /some/path/features/yellow.sch
    - name: lime
      path: /some/path/features/lime.sch
    - name: pink
      path: /some/path/features/pink.sch
    - name: gray
      path: /some/path/features/gray.sch
    - name: cyan
      path: /some/path/features/cyan.sch
  decor:
    - name: chest
      path: /some/path/features/decor.sch
    - name: furnace
      path: /some/path/features/furnace.sch
    - name: crafting
      path: /some/path/features/crafting.sch
    - name: stonecutter
      path: /some/path/features/stonecutter.sch
    - name: flowerpot
      path: /some/path/features/flowerpot.sch
    - name: shulkerbox
      path: /some/path/features/shulkerbox.sch
    - name: cartography
      path: /some/path/features/cartography.sch
    - name: cauldron
      path: /some/path/features/cauldron.sch
    - name: oaktrapdoor
      path: /some/path/features/oaktrapdoor.sch
    - name: smithing
      path: /some/path/features/smithing.sch