server:
  error:
    include-message: always

limits:
  building:
    height:
      min: ${BUILDING_HEIGHT_MIN:10}
      max: ${BUILDING_HEIGHT_MAX:40}

api:
  ws:
    schematics:
      endpoint: ${API_WS_SCHEMATIC_ENDPOINT:/ws/schematics}